# syntax=docker/dockerfile:1
#
# K2HASH
#
# Copyright 2013 Yahoo Japan Corporation.
#
# K2HASH is key-valuew store base libraries.
# K2HASH is made for the purpose of the construction of
# original KVS system and the offer of the library.
# The characteristic is this KVS library which Key can
# layer. And can support multi-processing and multi-thread,
# and is provided safely as available KVS.
#
# For the full copyright and license information, please view
# the license file that was distributed with this source code.
#
# AUTHOR:   Takeshi Nakatani
# CREATE:   Tue, Aug 10 2021
# REVISION:
#

# [NOTE]
# This file expects the following variables to be expanded by autoconf.
#	PACKAGE_NAME
#
# Also, replace the following variables.
#	DOCKER_IMAGE_BASE			(ex. "antpickax/libfullock:latest")
#	DOCKER_IMAGE_DEV_BASE		(ex. "antpickax/libfullock-dev:latest")
#	PRE_PROCESS					(ex. ":")
#	POST_PROCESS				(ex. ":")
#	IMAGE_CMD_BASE				(ex. "['/bin/sh', '-c', 'tail -f /dev/null']" as default)
#	IMAGE_CMD_DEV				(ex. "['/bin/sh', '-c', 'tail -f /dev/null']" as default)
#	PKG_UPDATE					(ex. "apk update -q --no-progress")
#	PKG_INSTALL_CURL			(ex. "apk add -q --no-progress --no-cache git build-base openssl libtool automake autoconf procps")
#	PKG_INSTALL_BASE			(ex. "apk add -q --no-progress --no-cache antpickax-package...")
#	PKG_INSTALL_DEV				(ex. "apk add -q --no-progress --no-cache antpickax-dev-package...")
#	SETUP_PC_REPO				(ex. "curl -s https://packagecloud.io/install/repositories/yahoojapan/stable/script.alpine.sh | sh")
#	SETUP_ENV					(ex. "ENV DEBIAN_FRONTEND=noninteractive")
#	UPDATE_LIBPATH				(ex. "ldconfig", if want no-operation, specify ":")
#	PKG_UNINSTALL_BASE			(ex. "apk del package...")
#	PKG_UNINSTALL_DEV			(ex. "apk del package...")

#
# Image for development
#
FROM %%DOCKER_IMAGE_DEV_BASE%% AS @PACKAGE_NAME@-dev

MAINTAINER antpickax
WORKDIR /

%%SETUP_ENV%%

RUN set -x && \
	%%PRE_PROCESS%% && \
	%%PKG_UPDATE%% && \
	%%PKG_INSTALL_CURL%% && \
	%%SETUP_PC_REPO%% && \
	%%PKG_INSTALL_DEV%% && \
	%%UPDATE_LIBPATH%% && \
	%%PKG_UNINSTALL_DEV%% && \
	%%POST_PROCESS%%

CMD %%IMAGE_CMD_DEV%%

#
# Image for main
#
FROM %%DOCKER_IMAGE_BASE%% AS @PACKAGE_NAME@

MAINTAINER antpickax
WORKDIR /

%%SETUP_ENV%%

RUN set -x && \
	%%PRE_PROCESS%% && \
	%%PKG_UPDATE%% && \
	%%PKG_INSTALL_CURL%% && \
	%%SETUP_PC_REPO%% && \
	%%PKG_INSTALL_BASE%% && \
	%%UPDATE_LIBPATH%% && \
	%%PKG_UNINSTALL_BASE%% && \
	%%POST_PROCESS%%

CMD %%IMAGE_CMD_BASE%%

#
# Local variables:
# tab-width: 4
# c-basic-offset: 4
# End:
# vim600: noexpandtab sw=4 ts=4 fdm=marker
# vim<600: noexpandtab sw=4 ts=4
#
