.TH K2HIMPORT "1" "February 2014" "K2HASH" "NoSQL(KVS) Library"
.SH NAME
K2HIMPORT \- Utility Tool for K2HASH by Yahoo! JAPAN
.SH SYNOPSIS
.B k2himport
[ \-h ]
.TP
.B k2himport
INPUTFILE OUTPUTFILE [ -mdbm ]
.SH DESCRIPTION
.PP
k2himport is a tool for import from text file to K2HASH file.
.SH OPTIONS
.TP
\fB\-h\fR
display help
.TP
\fB-mdbm\fR
import from mdbm_export format text file.
.TP
.SH SEE ALSO
.TP
k2hash(1), k2hlinetool(1), k2hreplace(1), k2hcompress(1), k2hedit(1) , k2htouch(1)
.SH BUGS
.TP
Please report owner and comitter.
.SH AUTHOR
k2himport has been written by Tetsuya Mochizuki <temochiz@yahoo-corp.jp>.
