.TH K2HREPLACE "1" "February 2014" "K2HASH" "NoSQL(KVS) Library"
.SH NAME
K2HREPLACE \- Utility Tool for K2HASH by Yahoo! JAPAN
.SH SYNOPSIS
.B k2hreplace
[ \-d ] SOURCE_FILE DESTINATION_FILE
.SH DESCRIPTION
.PP
k2hreplace is a tool for replacing K2HASH file safty when another processes are using it. After doing, destination file is moved with suffix.
.SH OPTIONS
.TP
\fBSOURCE_FILE\fR
specify source k2hash file path
.TP
\fBDESTINATION_FILE\fR
specify destination k2hash file path
.TP
\fB\-d\fR
run with debugging mode
.SH ENVIRONMENT
.TP
\fBK2HDBGMODE\fR
K2HDBGMODE environment sets debugging message level as same as \-g option. The value is set as SILENT, ERR, WAN or INFO.
When k2hlinetool catches SIGUSER1 signal, the debugging message level is bumpup. The level is changed as order by SILENT, ERR, WAN, INFO, SILENT...
.TP
\fK2HDBGFILE\fR
K2HDBGFILE environment sets the file which is debugging message, this is as same as \-glog option.
.SH SEE ALSO
.TP
k2hash(1), k2hlinetool(1), k2hcompress(1), k2htouch(1), k2hedit(1)
.SH BUGS
.TP
Please report owner and comitter.
.SH AUTHOR
k2hash has been written by Takeshi Nakatani <ggtakec@gmail.com>.
